### ISSUE TITLE
Spelling mistake "perscribed"

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/refresher-on-mvc#8]
Not only are they named helpfully and live in helpfully-named directories like models/ and controllers/, but they encapsulate their responsibilities as **perscribed** in the MVC architecture.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
