### ISSUE TITLE
Why isn't this "refresher", along with many of the "review" videos, at the beginning of the Rails section? (As an into)

### ISSUE THREAD

**Issue by AudreyJones** [learn-co-curriculum/refresher-on-mvc#9]
Why isn't this at the beginning of our Rails curriculum? Along with many of the "review" videos, this would make delving into the convoluted and at times buggy labs, much more manageable and help fit what we're learning into the big picture of Rails and where it fits into the MVC architecture.

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
